## scikit-learn 中的 kNN 

In [69]:
import numpy as np
import matplotlib.pyplot as plt

In [70]:
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

### 使用scikit-learn中的kNN

In [71]:
from sklearn.neighbors import KNeighborsClassifier

In [72]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [73]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [74]:
x = np.array([8.093607318, 3.365731514])

In [75]:
X_test = x.reshape(1, -1)

In [76]:
X_test

array([[ 8.09360732,  3.36573151]])

In [77]:
kNN_classifier.predict(X_test)

array([1])

In [78]:
y_test = kNN_classifier.predict(X_test)

In [79]:
y_test[0]

1

### 重新整理我们的kNN的代码

代码参加 [这里](kNN/KNN.py)

In [80]:
%run kNN/kNN.py

In [81]:
knn_clf = KNNClassifier(3)

In [82]:
knn_clf.fit(X_train, y_train)

KNN(k=3)

In [83]:
y_test = knn_clf.predict(X_test)

In [84]:
y_test

array([1])

In [85]:
y_test[0]

1