## 09 ``Numpy`` 中arg运算

In [1]:
import numpy as np

In [27]:
x = np.random.normal(0, 1, 1000000)

### 索引

In [28]:
np.argmin(x)

886266

In [29]:
x[886266]

-4.8354963762015108

In [30]:
np.min(x)

-4.8354963762015108

In [31]:
np.argmax(x)

4851

In [33]:
x[4851]

4.5860138951376461

In [34]:
np.max(x)

4.5860138951376461

### 排序和使用索引

In [35]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
np.random.shuffle(x)
x

array([13,  2,  6,  7, 11, 10,  3,  4,  8,  0,  5,  1,  9, 14, 12, 15])

In [37]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
x

array([13,  2,  6,  7, 11, 10,  3,  4,  8,  0,  5,  1,  9, 14, 12, 15])

In [39]:
x.sort()

In [40]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
X = np.random.randint(10, size=(4,4))
X

array([[8, 8, 5, 8],
       [1, 2, 2, 4],
       [5, 5, 9, 9],
       [3, 9, 3, 4]])

In [42]:
np.sort(X, axis=0)

array([[1, 2, 2, 4],
       [3, 5, 3, 4],
       [5, 8, 5, 8],
       [8, 9, 9, 9]])

In [43]:
np.sort(X, axis=1)

array([[5, 8, 8, 8],
       [1, 2, 2, 4],
       [5, 5, 9, 9],
       [3, 3, 4, 9]])

#### 使用索引

In [44]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [45]:
np.random.shuffle(x)

In [46]:
x

array([14, 15,  8,  7, 10,  4,  9,  1,  6,  5,  3, 12,  2, 11,  0, 13])

In [47]:
np.argsort(x)

array([14,  7, 12, 10,  5,  9,  8,  3,  2,  6,  4, 13, 11, 15,  0,  1])

In [48]:
np.partition(x, 3)

array([ 1,  0,  2,  3,  4,  5,  7,  8,  6,  9, 10, 12, 11, 13, 15, 14])

In [49]:
np.argpartition(x, 3)

array([ 7, 14, 12, 10,  5,  9,  3,  2,  8,  6,  4, 11, 13, 15,  1,  0])

In [50]:
X

array([[8, 8, 5, 8],
       [1, 2, 2, 4],
       [5, 5, 9, 9],
       [3, 9, 3, 4]])

In [51]:
np.argsort(X, axis=1)

array([[2, 0, 1, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 2, 3, 1]])

In [52]:
np.argpartition(X, 2, axis=1)

array([[2, 1, 0, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 2, 3, 1]])