## 03 ``numpy`` 基础

In [1]:
import numpy

In [2]:
numpy.__version__

'1.12.1'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.12.1'

### Python List的特点

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[5]

5

In [8]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [10]:
L[5] = "Machine Learning"
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

Python的List不要求存储同样的类型，带来效率问题。

In [12]:
import array
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[5]

5

In [15]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [20]:
arr[5] = "Machine Learning"

TypeError: an integer is required (got type str)

In [22]:
arr[5] = 5.0

TypeError: integer argument expected, got float

``array``的缺点是没有将数据当做向量或者矩阵，不支持基本运算。

### ``np.array``

In [17]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [19]:
nparr[5] = "Machine Learning"

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [23]:
nparr.dtype

dtype('int64')

In [25]:
nparr[5] = 5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
nparr.dtype

dtype('int64')

In [28]:
nparr[5] = 3.14
nparr

array([0, 1, 2, 3, 4, 3, 6, 7, 8, 9])

In [31]:
nparr2 = np.array([1, 2, 3.0])
nparr2.dtype

dtype('float64')

### 其他创建 ``np.array`` 的方法

#### ``zeros``

In [32]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [33]:
np.zeros(10, dtype=float)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### ones

In [34]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [36]:
np.ones((3, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

#### full

In [57]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [62]:
np.full(fill_value=666, shape=(3, 5))

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

#### arange

In [42]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [48]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [49]:
np.arange(0, 1, 0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

#### linspace

In [47]:
np.linspace(0, 20, 10)

array([  0.        ,   2.22222222,   4.44444444,   6.66666667,
         8.88888889,  11.11111111,  13.33333333,  15.55555556,
        17.77777778,  20.        ])

In [50]:
np.linspace(0, 20, 11)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.])

In [51]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

#### random

##### randint

In [67]:
np.random.randint(0, 10)    # [0, 10)之间的随机数

2

In [68]:
np.random.randint(0, 10, 10)

array([6, 8, 7, 8, 4, 4, 3, 1, 0, 0])

In [70]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
np.random.randint(0, 10, size=10)

array([3, 6, 1, 1, 7, 0, 1, 0, 1, 1])

In [66]:
np.random.randint(0, 10, size=(3,5))

array([[1, 6, 7, 6, 4],
       [2, 1, 6, 3, 8],
       [6, 2, 7, 3, 9]])

##### seed

In [71]:
np.random.seed(666)

In [78]:
np.random.randint(0, 10, size=(3, 5))

array([[7, 5, 2, 2, 2],
       [6, 8, 5, 8, 5],
       [1, 4, 8, 4, 3]])

In [74]:
np.random.seed(666)
np.random.randint(0, 10, size=(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

##### random

In [80]:
np.random.random()

0.9626746812565987

In [81]:
np.random.random((3,5))

array([[ 0.19705023,  0.71458996,  0.16192394,  0.86625477,  0.62382025],
       [ 0.95945512,  0.52414204,  0.03643288,  0.72687158,  0.00390984],
       [ 0.050294  ,  0.99199232,  0.2122575 ,  0.94737066,  0.45154055]])

##### normal

In [82]:
np.random.normal()

0.39638567394159424

In [86]:
np.random.normal(10, 100)

81.1504149558854

In [76]:
np.random.normal(0, 1, (3, 5))

array([[-1.47693162, -0.70022971,  0.77605168,  1.18063598,  0.06102404],
       [ 1.07856138, -0.79783572,  1.1701326 ,  0.1121217 ,  0.03185388],
       [-0.19206285,  0.78611284, -1.69046314, -0.98873907,  0.31398563]])

np.random.<TAB> 查看random中的更多方法

In [87]:
np.random?