## 05 ``numpy.array`` 基本操作

In [1]:
import numpy as np
np.random.seed(0)

x = np.arange(10)

In [2]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
X = np.arange(15).reshape((3, 5))

In [4]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### ``numpy.array`` 的基本属性

In [5]:
x.ndim

1

In [6]:
X.ndim

2

In [7]:
x.shape

(10,)

In [8]:
X.shape

(3, 5)

In [9]:
x.size

10

In [10]:
X.size

15

### ``numpy.array`` 的数据访问

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x[0]

0

In [13]:
x[-1]

9

In [14]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
X[0][0] # 不建议！

0

In [16]:
X[0, 0]

0

In [17]:
X[0, -1]

4

In [18]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x[0:5]

array([0, 1, 2, 3, 4])

In [20]:
x[:5]

array([0, 1, 2, 3, 4])

In [21]:
x[5:]

array([5, 6, 7, 8, 9])

In [22]:
x[4:7]

array([4, 5, 6])

In [23]:
x[::2]

array([0, 2, 4, 6, 8])

In [24]:
x[1::2]

array([1, 3, 5, 7, 9])

In [25]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [28]:
X[:2][:3] # 结果不一样，在numpy中使用","做多维索引

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [30]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [31]:
X[0, :]

array([0, 1, 2, 3, 4])

In [32]:
X[:, 0]

array([ 0,  5, 10])

### Subarray of ``numpy.array``

In [33]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [34]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [35]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [36]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [38]:
subX = X[:2, :3].copy()

In [39]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [40]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [41]:
x.shape

(10,)

In [42]:
x.ndim

1

In [43]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [48]:
B.ndim

2

In [49]:
B.shape

(1, 10)

In [50]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [52]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)