## 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 

In [2]:
iris_data = datasets.load_iris()
iris_data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [3]:
X = iris_data.data

In [4]:
X.shape

(150, 4)

In [5]:
y = iris_data.target

In [6]:
y.shape

(150,)

### train_test_split

如果我们使用X来训练我们的kNN算法，当k=1时，我们的算法在X上是100%正确的。

解决方案：分离出一部分数据做训练，另外一部分数据做测试。

In [7]:
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes

array([ 93,  15,  91, 141,  75,  62,  22, 106,  30,  20, 100,  89, 115,
        73, 113,   8,  90, 138,  97,  37,  17,  88, 134,  87,  98, 132,
        38,  96,   2,   1,  39, 116, 110,  53,  43,  59,  48, 127,  77,
        29, 108,   3, 131, 112,  21, 125,  47,  70, 142,  94, 136, 123,
        44, 101, 111,  72,  35,  11, 145,  95,  86,  58, 146, 147, 105,
        10, 104,  81, 121, 109,  27, 117,  69, 102, 140, 124,   4, 139,
       107,  76,  24,  23,  82,  54,  56, 126,  32,   5,  18,  64,  46,
        31,  71, 143,  78,  26, 133,  13,  63,  45,  33,  67, 135, 129,
        57,  99,  25, 130,  40,   0,  80,  42,  50,  68,  51, 118,  55,
        19, 148,  12,   6,  79,  83,  84, 149, 119,  49,  34,  14, 122,
       128,   9,  92,  61, 103,  66,  65,  85, 144, 137,  28,  74,  52,
       120, 114,   7,  41,  16,  60,  36])

In [8]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [9]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]

In [10]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [11]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [12]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 封装

In [13]:
from playML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [14]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [15]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### sklearn中的train_test_split

In [16]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split>

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [23]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [24]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 测试我们的算法

In [25]:
from playML.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [26]:
y_predict

array([1, 1, 1, 0, 2, 0, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 2, 0, 0, 0, 1, 0,
       0, 2, 2, 0, 2, 0, 1])

In [27]:
y_test

array([1, 1, 1, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 1, 2, 1, 1, 2, 0, 0, 0, 1, 0,
       0, 2, 2, 0, 2, 0, 1])

In [28]:
sum([1 if y_predict[i] == y_test[i] else 0 for i in range(len(y_test))])

29

In [29]:
sum([1 if y_predict[i] == y_test[i] else 0 for i in range(len(y_test))]) / len(y_test)

0.9666666666666667