## 10 ``Numpy`` 中的比较和Fancy Indexing

### Fancy Indexing

In [2]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
x[3]

3

In [5]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [6]:
x[3:9:2]

array([3, 5, 7])

In [7]:
[x[3], x[5], x[7]]

[3, 5, 7]

In [8]:
ind = [3, 5, 7]
x[ind]

array([3, 5, 7])

In [9]:
ind = np.array([[0, 2], [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

#### Fancy Indexing 应用在二维数组

In [10]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [12]:
X[0, col]

array([1, 2, 3])

In [13]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [15]:
col = [True, False, True, True]

In [16]:
X[0, col]

array([0, 2, 3])

### ``numpy.array`` 的比较

In [17]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False], dtype=bool)

In [19]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [20]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False], dtype=bool)

In [21]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [22]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False], dtype=bool)

In [23]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [28]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False], dtype=bool)

In [29]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]], dtype=bool)

### 使用 ``numpy.array`` 的比较结果 

In [30]:
np.count_nonzero( x <= 3)

4

In [32]:
np.sum(x <= 3)

4

In [33]:
np.sum(X % 2 == 0, axis=0)

array([4, 0, 4, 0])

In [34]:
np.sum(X % 2 == 0, axis=1)

array([2, 2, 2, 2])

In [37]:
np.any(x == 0)

True

In [38]:
np.any(x < 0)

False

In [39]:
np.all(x > 0)

False

In [40]:
np.all(x >= 0)

True

In [41]:
np.all(X > 0, axis=1)

array([False,  True,  True,  True], dtype=bool)

In [44]:
np.sum((x > 3) & (x < 10))

6

In [45]:
np.sum((x > 3) && (x < 10))

SyntaxError: invalid syntax (<ipython-input-45-780ca9b7c144>, line 1)

In [46]:
np.sum((x % 2 == 0) | (x > 10))

11

In [47]:
np.sum(~(x == 0))

15

### 比较结果和Fancy Indexing

In [17]:
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False], dtype=bool)

In [18]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [20]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [21]:
X[X[:,3] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])