## ``Numpy`` 中的聚合操作

### sum

In [1]:
import numpy as np

L = np.random.random(100)
sum(L)

50.402951975687742

In [2]:
np.sum(L)

50.402951975687749

In [3]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

10 loops, best of 3: 120 ms per loop
1000 loops, best of 3: 624 µs per loop


### min, max

In [7]:
np.min(big_array)

7.8687986404535337e-07

In [8]:
np.max(big_array)

0.99999791004378091

In [9]:
big_array.min()

7.8687986404535337e-07

In [10]:
big_array.max()

0.99999791004378091

In [12]:
big_array.sum()

500287.23763296654

In [14]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
X = np.reshape(np.arange(16), (-1,4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 多维度聚合

In [20]:
X.sum()

120

In [21]:
X.sum(axis=0)

array([24, 28, 32, 36])

In [22]:
X.sum(axis=1)

array([ 6, 22, 38, 54])

注意：axis描述的是将要被压缩的维度。

### 其他聚合操作

In [30]:
X.prod()

0

In [31]:
(X+1).prod()

20922789888000

In [26]:
X.mean()

7.5

In [35]:
np.median(X)

7.5

In [38]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2000000000000002

In [39]:
np.median(v)

2.0

In [57]:
np.percentile(big_array, q=50)

0.50046052856364909

In [58]:
np.median(big_array)

0.50046052856364909

In [55]:
np.percentile(big_array, q=100)

0.99999791004378091

In [56]:
np.max(big_array)

0.99999791004378091

In [61]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

7.86879864045e-07
0.250298330237
0.500460528564
0.750488292268
0.999997910044


In [63]:
np.var(big_array)

0.083328703671875115

In [64]:
np.std(big_array)

0.28866711567456921

In [65]:
x = np.random.normal(0, 1, 1000000)

In [66]:
np.mean(x)

0.001245399105871569

In [67]:
np.std(x)

1.0007758602297387

In [68]:
np.argmin(x)

94728

In [69]:
x[94728]

-4.4960745835192393

In [70]:
x.min()

-4.4960745835192393

In [71]:
np.argmax(x)

929964