## 简单的 Numpy Broadcasting

Broadcasting（广播） 解决的是不同形状的矩阵（或者向量）之间的运算问题。

在代数运算中，不同形状的矩阵（或者向量）之间无法进行基本运算，但是在Numpy中，只要满足一般规则，这个运算的允许的。

In [1]:
import numpy as np

#### 向量和一个数字相加

```
a = [a1, a2, a3]
b

c = a + b
c = [a1 + b, a2 + b, a3 + b]
```

In [2]:
a = np.array([1, 2, 3])
b = 2
a + b

array([3, 4, 5])

#### 二维数组和一个数字相加

```
A = [[a11, a12, a13],
     [a21, a22, a23]]
b

C = A + b
C = [[a11 + b, a12 + b, a13 + b],
     [a21 + b, a22 + b, a23 + b]]
```

In [3]:
A = np.array([[1, 2, 3],
             [1, 2, 3]])
b = 2
C = A + b
C

array([[3, 4, 5],
       [3, 4, 5]])

#### 二维数组和一维数组相加

```
A = [[a11, a12, a13],
     [a21, a22, a23]]
b = [b1, b2, b3]

C = A + b
C = [[a11 + b1, a12 + b2, a13 + b3],
     [a21 + b1, a22 + b2, a23 + b3]]
```

In [4]:
A = np.array([[1, 2, 3],
              [1, 2, 3]])
b = np.array([1, 2, 3])
C = A + b
C

array([[2, 4, 6],
       [2, 4, 6]])

### Broadcasting的基本原则

整体而言，两个不同形状的矩阵（或者向量）进行基本运算，看两个矩阵（或者向量）的倒序维数。如果**倒序维数是一致的**，则“小矩阵”经过复制扩展，和“大矩阵”进行基本运算。

比如：

```
A.shape = (2 x 3)  ->  A.shape = (2 x 3)
b.shape = (3)      ->  b.shape = (1 x 3)

A.shape = (2 x 3)  ->  A.shape = (2 x 3)
b.shape = (1)      ->  b.shape = (1 x 1)
```

但是，在以下例子中，b无法broadcasting后和A进行运算

```
A.shape = (2 x 3)
b.shape = (1 x 2)
```

In [5]:
A = np.array([[1, 2, 3],
              [1, 2, 3]])
b = np.array([1, 2])
C = A + b
C

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 