## 08 ``Numpy`` 中的聚合操作

### sum

In [1]:
import numpy as np

L = np.random.random(100)
sum(L)

52.675554310672098

In [2]:
np.sum(L)

52.675554310672105

In [3]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

10 loops, best of 3: 173 ms per loop
1000 loops, best of 3: 1.02 ms per loop


### min, max

In [4]:
np.min(big_array)

2.2765289564574687e-07

In [5]:
np.max(big_array)

0.99999686126703025

In [6]:
big_array.min()

2.2765289564574687e-07

In [7]:
big_array.max()

0.99999686126703025

In [8]:
big_array.sum()

500454.89231729991

### 多维度聚合

In [9]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.sum(X)

120

In [11]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [12]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

注意：axis描述的是将要被压缩的维度。

### 其他聚合操作

In [13]:
np.prod(X)

0

In [14]:
np.prod(X + 1)

20922789888000

In [15]:
np.mean(X)

7.5

In [16]:
np.median(X)

7.5

In [17]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2000000000000002

In [18]:
np.median(v)

2.0

In [19]:
np.percentile(big_array, q=50)

0.50056612640031206

In [20]:
np.median(big_array)

0.50056612640031206

In [21]:
np.percentile(big_array, q=100)

0.99999686126703025

In [22]:
np.max(big_array)

0.99999686126703025

In [23]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

2.27652895646e-07
0.250501365819
0.5005661264
0.750543416185
0.999996861267


In [24]:
np.var(big_array)

0.083379660489048227

In [25]:
np.std(big_array)

0.28875536443336985

In [26]:
x = np.random.normal(0, 1, 1000000)

In [27]:
np.mean(x)

-0.00044876833100538597

In [28]:
np.std(x)

1.0000457010611321