## 04 ``numpy`` Basic Operations

In [31]:
import numpy as np
np.random.seed(0)

X1 = np.arange(10)

In [33]:
X1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
X2 = np.arange(15).reshape((3, 5))

In [37]:
X2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### ``numpy.array`` 的基本属性

In [38]:
X1.ndim

1

In [39]:
X2.ndim

2

In [40]:
X1.shape

(10,)

In [41]:
X2.shape

(3, 5)

In [42]:
X1.size

10

In [43]:
X2.size

15

In [44]:
X1.dtype

dtype('int64')

### ``numpy.array`` 的数据访问

In [45]:
X1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
X1[0]

0

In [47]:
X1[-1]

9

In [48]:
X2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
X2[0][0]

0

In [50]:
X2[0, 0]

0

In [51]:
X2[0, -1]

4

In [59]:
X1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
X1[0:5]

array([0, 1, 2, 3, 4])

In [53]:
X1[:5]

array([0, 1, 2, 3, 4])

In [54]:
X1[5:]

array([5, 6, 7, 8, 9])

In [55]:
X1[4:7]

array([4, 5, 6])

In [56]:
X1[::2]

array([0, 2, 4, 6, 8])

In [57]:
X1[1::2]

array([1, 3, 5, 7, 9])

In [58]:
X1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [60]:
X2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
X2[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [62]:
X2[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [63]:
X2[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [64]:
X2[0, :]

array([0, 1, 2, 3, 4])

In [65]:
X2[:, 0]

array([ 0,  5, 10])

### Subarray of ``np.array``

In [66]:
subx = X2[:2, :3]
subx

array([[0, 1, 2],
       [5, 6, 7]])

In [68]:
subx[0, 0] = 100
subx

array([[100,   1,   2],
       [  5,   6,   7]])

In [69]:
X2

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [71]:
X2[0, 0] = 0
X2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [72]:
subx

array([[0, 1, 2],
       [5, 6, 7]])

In [73]:
subx = X2[:2, :3].copy()

In [74]:
subx[0, 0] = 100
subx

array([[100,   1,   2],
       [  5,   6,   7]])

In [75]:
X2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [76]:
X1.shape

(10,)

In [77]:
X1.ndim

1

In [78]:
X1.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
X1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
A = X1.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
X1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
A = X1.reshape(1, 10)
A

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [86]:
A.ndim

2

In [87]:
A.shape

(1, 10)

### ``np.array`` 的合并

In [88]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [89]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [90]:
z = np.array([666, 666, 666])
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [92]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [93]:
np.concatenate([a, a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [94]:
np.concatenate([a, z])

ValueError: all the input arrays must have same number of dimensions

In [95]:
np.vstack([a, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [98]:
b = np.full((2,2), 100)

In [99]:
np.hstack([a, b])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [100]:
np.hstack([a, z])

ValueError: all the input arrays must have same number of dimensions

### ``np.array`` 的分割

In [102]:
x = np.arange(10)
x    

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
x1, x2, x3 = np.split(x, [3, 7])

In [105]:
x1

array([0, 1, 2])

In [106]:
x2

array([3, 4, 5, 6])

In [107]:
x3

array([7, 8, 9])

In [108]:
x1, x2 = np.split(x, [5])

In [109]:
x1

array([0, 1, 2, 3, 4])

In [110]:
x2

array([5, 6, 7, 8, 9])

In [112]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [113]:
upper, lower = np.vsplit(A, [2])

In [114]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [115]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [116]:
left, right = np.hsplit(A, [2])

In [117]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [118]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])