## 更多numpy的使用方式

### 关于numpy比较结果的逻辑组合

In [1]:
import numpy as np
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### 课程中使用的方式

In [2]:
np.sum((x < 3) | (x > 10))

8

In [3]:
np.sum((x > 3) & (x < 10))

6

In [4]:
np.sum(~(x > 3))

4

#### 另外的方式，``logical_and``, ``logical_or``

In [5]:
np.logical_or(x < 3, x > 10)

array([ True,  True,  True, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True], dtype=bool)

In [6]:
np.sum(np.logical_or(x < 3, x > 10))

8

In [7]:
np.logical_and(x > 3, x < 10)

array([False, False, False, False,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False], dtype=bool)

In [8]:
np.sum(np.logical_and(x > 3, x < 10))

6

In [9]:
np.logical_not(x > 3)

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False], dtype=bool)

In [10]:
np.sum(np.logical_not(x > 3))

4