In [3]:
import numpy as np
from sklearn import datasets

In [4]:
iris = datasets.load_iris()

In [9]:
iris.data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)

In [13]:
X_train.shape

(120, 4)

In [14]:
y_train.shape

(120,)

In [15]:
X_test.shape

(30, 4)

In [16]:
y_test.shape

(30,)

### scikit-learn中的StandardScaler

In [6]:
from sklearn.preprocessing import StandardScaler 

In [7]:
standardScalar = StandardScaler() 

In [27]:
standardScalar.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [28]:
standardScalar.mean_

array([ 5.8275    ,  3.05333333,  3.71333333,  1.18166667])

In [29]:
standardScalar.scale_

array([ 0.77899107,  0.43434497,  1.71866874,  0.7462108 ])

In [30]:
np.mean(X_train[:,0])

5.8275000000000006

In [31]:
np.std(X_train[:,0])

0.77899106755683245

In [32]:
X_train

array([[ 5.5,  2.4,  3.8,  1.1],
       [ 6.9,  3.1,  5.1,  2.3],
       [ 6.1,  3. ,  4.9,  1.8],
       [ 5.9,  3.2,  4.8,  1.8],
       [ 6.3,  3.3,  4.7,  1.6],
       [ 6.7,  3.1,  5.6,  2.4],
       [ 6.8,  3.2,  5.9,  2.3],
       [ 6.2,  2.2,  4.5,  1.5],
       [ 7. ,  3.2,  4.7,  1.4],
       [ 6.3,  3.4,  5.6,  2.4],
       [ 6.2,  2.8,  4.8,  1.8],
       [ 5. ,  3.3,  1.4,  0.2],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.8,  2.7,  5.1,  1.9],
       [ 6.7,  3. ,  5. ,  1.7],
       [ 6.4,  3.2,  5.3,  2.3],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 5.5,  2.5,  4. ,  1.3],
       [ 7.4,  2.8,  6.1,  1.9],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 5.9,  3. ,  5.1,  1.8],
       [ 6.1,  2.8,  4. ,  1.3],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.8,  2.7,  4.1,  1. ],
       [ 5.6,  2.9,  3.6,  1.3],
       [ 5.5,  4.2,  1.4,  0.2],
       [ 4.8,  3. ,  1.4,  0.3],
       [ 5. ,  3.2,  1.2,  0.2],
       [ 4.8,  3.1,  1.6,  0.2],
       [ 6. ,  2.7,  5.1,  1.6],
       [ 5

In [35]:
X_train = standardScalar.transform(X_train)

In [36]:
X_train

array([[-0.4204156 , -1.50418072,  0.05042663, -0.10944182],
       [ 1.37678087,  0.10744148,  0.80682603,  1.49868286],
       [ 0.34981146, -0.12279026,  0.69045689,  0.82863091],
       [ 0.0930691 ,  0.33767322,  0.63227232,  0.82863091],
       [ 0.60655381,  0.56790496,  0.57408775,  0.56061013],
       [ 1.12003852,  0.10744148,  1.09774887,  1.63269325],
       [ 1.24840969,  0.33767322,  1.27230258,  1.49868286],
       [ 0.47818263, -1.9646442 ,  0.45771861,  0.42659974],
       [ 1.50515205,  0.33767322,  0.57408775,  0.29258935],
       [ 0.60655381,  0.79813671,  1.09774887,  1.63269325],
       [ 0.47818263, -0.58325375,  0.63227232,  0.82863091],
       [-1.06227149,  0.56790496, -1.34600303, -1.31553533],
       [-0.93390031,  1.71906368, -1.28781847, -1.18152494],
       [-0.03530207, -0.81348549,  0.80682603,  0.9626413 ],
       [ 1.12003852, -0.12279026,  0.74864146,  0.69462052],
       [ 0.73492499,  0.33767322,  0.92319516,  1.49868286],
       [-0.93390031,  0.

In [37]:
X_test_standard = standardScalar.transform(X_test) 

In [39]:
X_test_standard

array([[ 0.60655381, -0.35302201,  1.09774887,  0.82863091],
       [-1.83249855,  0.33767322, -1.4041876 , -1.31553533],
       [-0.03530207, -0.81348549,  0.80682603,  0.9626413 ],
       [-0.16367325, -1.27394898,  0.74864146,  1.09665169],
       [-1.06227149, -1.73441246, -0.24049622, -0.24345221],
       [-1.44738502,  0.33767322, -1.2296339 , -1.31553533],
       [ 2.66049264,  1.71906368,  1.56322543,  1.09665169],
       [ 0.60655381, -0.58325375,  0.80682603,  0.42659974],
       [ 0.60655381,  0.56790496,  1.33048715,  1.76670364],
       [-0.4204156 , -1.50418072, -0.00775794, -0.24345221],
       [-0.93390031,  1.71906368, -1.05508019, -1.04751455],
       [ 0.73492499,  0.33767322,  0.45771861,  0.42659974],
       [-1.06227149,  1.25860019, -1.34600303, -1.31553533],
       [-0.16367325,  1.71906368, -1.17144933, -1.18152494],
       [ 1.37678087,  0.10744148,  0.98137973,  1.23066208],
       [ 0.86329616, -0.12279026,  1.0395643 ,  0.82863091],
       [ 2.40375028, -1.

In [41]:
np.mean(X_test_standard[:,0])

0.10162718157341215

In [42]:
np.std(X_test_standard[:,0])

1.2664510399599134

使用归一化后的数据进行knn分类

In [47]:
from sklearn.neighbors import KNeighborsClassifier

In [48]:
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [49]:
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [51]:
knn_clf.score(X_test_standard, y_test)

0.96666666666666667

注意，此时不能传入没有归一化的数据！

In [53]:
knn_clf.score(X_test, y_test)

0.43333333333333335

### 实现我们自己的standardScaler